resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/gropax/Bougle.French.Glaff.git

- name: server-image
  type: docker-image
  icon: docker
  source:
    repository: nexus.boug.re:18444/bougle/bougle-fra-glaff
    username: ((docker-registry.username))
    password: ((docker-registry.password))
    tag: dev

jobs:
- name: build-and-test
  plan:
  - get: code
    trigger: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: mcr.microsoft.com/dotnet/sdk
          tag: "5.0"
      inputs:
      - name: code
      outputs:
      - name: code
      run:
        path: sh
        args:
        - -exc
        - |
          cd code
          dotnet restore Bougle.French.Glaff.sln
          dotnet build -c Release Bougle.French.Glaff.sln
          dotnet test -c Release Bougle.French.Glaff.sln

- name: build-server-image
  plan:
  - get: code
    passed: [build-and-test]
  - put: server-image
    params:
      build: code
      dockerfile: code/Bougle.French.Glaff.Web/Dockerfile
      labels:
        version: 1.0.1