resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/gropax/Bougle.French.Glaff.git

- name: server-image
  type: registry-image
  icon: docker
  source:
    repository: localhost:8082/bougle/fra-glaff

jobs:
- name: build-and-test
  plan:
  - get: code
    trigger: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: mcr.microsoft.com/dotnet/sdk
          tag: "5.0"
      inputs:
      - name: code
      outputs:
      - name: code
      run:
        path: sh
        args:
        - -exc
        - |
          cd code
          dotnet restore Bougle.French.Glaff.sln
          dotnet build -c Release Bougle.French.Glaff.sln
          dotnet test -c Release Bougle.French.Glaff.sln

- name: build-server-image
  plan:
  - get: code
    passed: [build-and-test]
  - task: build-server-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: code
      outputs:
      - name: image
      params:
        CONTEXT: code
        DOCKERFILE: code/Bougle.French.Glaff.Web/Dockerfile
      run:
        path: build
  - put: server-image
    params:
      image: image/image.tar
      version: "1.0.0"