platform: linux
image_resource:
  type: registry-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: "((framework))"
inputs:
- name: "((source))"
outputs:
- name: "((source))"
run:
  path: sh
  args:
  - -exc
  - |
    ln -s / /rootfs  # Fix tricky bug https://stackoverflow.com/q/71709759/19017361
    cd code
    dotnet test -c Release ((solution))