version: '3.4'

services:
  catalog-advisor:
    image: nexus.boug.re:18444/pragma/catalog-advisor:latest
    container_name: catalog-advisor
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - VIRTUAL_HOST=scenes.boug.re
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=scenes.boug.re
      - LETSENCRYPT_EMAIL=maxime.laudrin@protonmail.com

  catalog-advisor-db:
    image: neo4j:4.3.2-enterprise
    container_name: catalog-advisor-db
    restart: unless-stopped
    ports:
      - "17474:7474"
      - "17687:7687"
    volumes:
      - catalog-advisor-db-data:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - VIRTUAL_HOST=neo4j.boug.re
      - VIRTUAL_PORT=7474
      - LETSENCRYPT_HOST=neo4j.boug.re
      - LETSENCRYPT_EMAIL=maxime.laudrin@protonmail.com

volumes:
  catalog-advisor-db-data:

networks:
  default:
    external:
      name: nginx-proxy