version: '3.4'

services:
  catalog-advisor:
    image: nexus.boug.re:18444/pragma/catalog-advisor:latest
    container_name: catalog-advisor
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - Elasticsearch__Address=http://catalog-advisor-db:9200
      - VIRTUAL_HOST=scenes.boug.re
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=scenes.boug.re
      - LETSENCRYPT_EMAIL=maxime.laudrin@protonmail.com

  catalog-advisor-db:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9201:9200"
    volumes:
      - catalog-advisor-db-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - rootLogger.level=debug
      - VIRTUAL_HOST=catalog-advisor-db.boug.re
      - VIRTUAL_PORT=9200
      - LETSENCRYPT_HOST=catalog-advisor-db.boug.re
      - LETSENCRYPT_EMAIL=maxime.laudrin@protonmail.com
    mem_reservation: 2g
    mem_limit: 4g


volumes:
  catalog-advisor-db-data:

networks:
  default:
    external:
      name: nginx-proxy