version: '3.4'

services:
  catalog-advisor:
    image: nexus.boug.re:18444/bougle/cervel:latest
    container_name: cervel
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - VIRTUAL_HOST=cervel.boug.re
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cervel.boug.re
      - LETSENCRYPT_EMAIL=maxime.laudrin@protonmail.com

networks:
  default:
    external:
      name: nginx-proxy